apiVersion: v1
kind: ReplicationController
metadata:
  name: drone-server
  labels:
    heritage: drone-demos
spec:
  replicas: 1
  selector:
    name: drone-server
  template:
    metadata:
      labels:
        name: drone-server
    spec:
      containers:
        - image: drone/drone:0.4
          imagePullPolicy: Always
          name: drone-server
          env:
            - name: SERVER_ADDR
              value: ":80"
            - name: DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: drone
                  key: drone.database.driver
            - name: DATABASE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: drone
                  key: drone.database.config
            - name: REMOTE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: drone
                  key: drone.remote.driver
            - name: REMOTE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: drone
                  key: drone.remote.config
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            # Persist our configs in an SQLite DB in here
            - mountPath: /var/lib/drone
              name: drone-server-sqlite-db
            # Enables Docker in Docker
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
        - name: drone-server-sqlite-db
          gcePersistentDisk:
            pdName: drone-server-sqlite-db
            fsType: ext4
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
