apiVersion: v1
kind: Service
metadata:
  name: drone-server-internal
  labels:
    provider: drone-server-internal
    heritage: drone-demos
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    name: drone-server
